logging:
  level: TRACE

server:
  port: 5015

application:
  name: hangout-content-delivery-api

aws:
  region:
  image:
    s3:
      bucket:
  video:
    cloudfront:
      privateKeyPath:
      publicKeyID: 
      domain:
      expirationDurationInSeconds:

storage:
  content:
    endpoint: 
    accessKey:
    secretKey:
    isSecure:
  photo:
    endpoint: 
    accessKey:
    secretKey:
    isSecure: