logging:
  level: TRACE

server:
  port: 5015

application:
  name: hangout-content-delivery-api

aws:
  region:
  image:
    s3:
      bucket:
  video:
    cloudfront:
      privateKeyPath:
      publicKeyId: 
      domain:
      expirationDurationInSeconds:

otel:
  endpoint: localhost:4317