logging:
  level: TRACE

server:
  port: 5015

application:
  name: hangout-content-delivery-api

aws:
  region:
  image:
    s3:
      bucket:
      expiration-duration-seconds:
  video:
    cloudfront:
      private-key-path:
      public-key-id:
      domain:
      expiration-duration-seconds:

cookie:
  domain:      

otel:
  endpoint:
